SLNRegisterBundle:
    resource: "@SLNRegisterBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user: 
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rest:
    type: rest
    resource : "routing_rest.yml"
    prefix: /api

oneup_uploader:
    resource: .
    type: uploader

